"""Regenerate src/schema.sql from migrations/ as a current-state snapshot.

The migration files are the source of truth. This script just concatenates
them so humans browsing the repo (or DBAs spinning up a dev DB outside the
bot) have a single-file view of the current schema.

Run from the repo root:
    python scripts/regenerate_schema.py
"""
import sys
from pathlib import Path


HEADER = """\
-- AUTOGENERATED from migrations/. Do not edit this file directly.
-- To change the schema, add a new migrations/NNNN_description.sql file
-- and re-run scripts/regenerate_schema.py.
--
-- The bot itself applies pending migrations at boot — running this SQL
-- by hand against a live DB is no longer required.

"""


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    migrations_dir = repo_root / "migrations"
    schema_path = repo_root / "src" / "schema.sql"

    # Exclude reverse migrations: Path("x.down.sql").suffix is still ".sql",
    # so a bare suffix check would concatenate down files into the snapshot
    # (sorted before their forward file), corrupting it.
    files = sorted(
        p for p in migrations_dir.iterdir()
        if p.suffix == ".sql" and not p.name.endswith(".down.sql")
    )
    if not files:
        print(f"no migration files found in {migrations_dir}", file=sys.stderr)
        return 1

    parts = [HEADER]
    for path in files:
        parts.append(f"-- ── {path.name} ──\n")
        body = path.read_text(encoding="utf-8").rstrip()
        parts.append(body + "\n\n")

    schema_path.write_text("".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {schema_path} from {len(files)} migration file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
