-- AUTOGENERATED from migrations/. Do not edit this file directly.
-- To change the schema, add a new migrations/NNNN_description.sql file
-- and re-run scripts/regenerate_schema.py.
--
-- The bot itself applies pending migrations at boot — running this SQL
-- by hand against a live DB is no longer required.

-- ── 0001_baseline.sql ──
-- 0001_baseline: full schema as of the start of the migration system.
-- On an existing prod DB, this migration is detected as already-applied
-- (heuristic: economy_users present, schema_migrations empty) and recorded
-- without execution. On a fresh DB it creates everything below.

CREATE TABLE IF NOT EXISTS economy_users (
    user_id        BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    balance        BIGINT          NOT NULL DEFAULT 0,
    last_daily     DOUBLE          NOT NULL DEFAULT 0,
    daily_date     VARCHAR(10)     NULL,
    scratch_used   TINYINT         NOT NULL DEFAULT 0,
    scratch_date   VARCHAR(10)     NULL,
    jailbreak_used BOOLEAN         NOT NULL DEFAULT FALSE,
    jail_until     DOUBLE          NOT NULL DEFAULT 0,
    savings        JSON            NOT NULL DEFAULT (JSON_ARRAY())
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS economy_meta (
    key_name   VARCHAR(64) NOT NULL PRIMARY KEY,
    value_text TEXT        NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS guild_house_balance (
    guild_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    balance  BIGINT          NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS guild_settings (
    guild_id      BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    settings_json JSON            NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bot_roles (
    role_id BIGINT UNSIGNED NOT NULL PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS godmode_users (
    user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bot_settings (
    key_name   VARCHAR(64) NOT NULL PRIMARY KEY,
    value_text TEXT        NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS shop_insurance (
    user_id        BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    expires_at     DOUBLE          NOT NULL,
    protected_from JSON            NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS shop_effects (
    user_id      BIGINT UNSIGNED                           NOT NULL,
    effect_type  ENUM('ragebait','mock','curse','tax')     NOT NULL,
    remaining    INT          NULL,
    started_by   BIGINT UNSIGNED NULL,
    cursed_by    BIGINT UNSIGNED NULL,
    history_json JSON         NULL,
    master_id    BIGINT UNSIGNED NULL,
    tax_type     VARCHAR(64)  NULL,
    tax_emoji    VARCHAR(16)  NULL,
    channel_id   BIGINT UNSIGNED NULL,
    activated_at DOUBLE       NULL,
    PRIMARY KEY (user_id, effect_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rigged_slots (
    user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    symbol  VARCHAR(16)     NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rigged_flips (
    user_id        BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    remaining_wins INT             NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rigged_scratch (
    user_id       BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    symbols_count INT             NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rigged_steal (
    user_id              BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    remaining_successes  INT             NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS slots_jackpot (
    id      TINYINT NOT NULL PRIMARY KEY DEFAULT 1,
    jackpot BIGINT  NOT NULL DEFAULT 5000
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO slots_jackpot (id, jackpot) VALUES (1, 5000);

CREATE TABLE IF NOT EXISTS lottery (
    guild_id         BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    prize_pool       BIGINT          NOT NULL DEFAULT 0,
    last_posted_week INT             NOT NULL DEFAULT 0,
    last_drawn_week  INT             NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lottery_players (
    guild_id BIGINT UNSIGNED NOT NULL,
    user_id  BIGINT UNSIGNED NOT NULL,
    tickets  INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (guild_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS records (
    guild_id     BIGINT UNSIGNED NOT NULL,
    category     VARCHAR(64)     NOT NULL,
    value        BIGINT          NOT NULL,
    holder_id    BIGINT UNSIGNED NOT NULL,
    holder_name  VARCHAR(255)    NOT NULL,
    extra_json   JSON            NULL,
    PRIMARY KEY (guild_id, category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS channel_prompts (
    channel_id  BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    prompt_text TEXT            NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chess_games (
    channel_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    game_json  JSON            NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_threads (
    thread_id         BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    kind              ENUM('ask','story','roleplay','rpg') NOT NULL,
    owner_id          BIGINT UNSIGNED NOT NULL,
    guild_id          BIGINT UNSIGNED NULL,
    invited_ids_json  JSON            NOT NULL,
    system_prompt     TEXT            NULL,
    character_prompt  TEXT            NULL,
    history_json      JSON            NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS leveling (
    guild_id BIGINT UNSIGNED NOT NULL,
    user_id  BIGINT UNSIGNED NOT NULL,
    data     JSON            NOT NULL,
    PRIMARY KEY (guild_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS gambler_streak (
    user_id        BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    last_full_date VARCHAR(10)     NOT NULL,
    streak_count   INT             NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS quote_log (
    id         INT UNSIGNED    NOT NULL AUTO_INCREMENT PRIMARY KEY,
    content    TEXT            NOT NULL,
    created_at TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS saved_quotes (
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    guild_id   VARCHAR(20)     NOT NULL,
    quote_json JSON            NOT NULL,
    INDEX idx_guild (guild_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS balance_history (
    snapshot_date VARCHAR(10)     NOT NULL,
    user_id       BIGINT UNSIGNED NOT NULL,
    wallet        BIGINT          NOT NULL DEFAULT 0,
    savings       BIGINT          NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_date, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bot_stats_history (
    snapshot_date VARCHAR(10) NOT NULL PRIMARY KEY,
    messages      INT         NOT NULL DEFAULT 0,
    commands      INT         NOT NULL DEFAULT 0,
    ai_responses  INT         NOT NULL DEFAULT 0,
    ai_up         BOOLEAN     NOT NULL DEFAULT FALSE,
    memory_mb     FLOAT       NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS restart_msg (
    id         TINYINT         NOT NULL PRIMARY KEY DEFAULT 1,
    channel_id BIGINT UNSIGNED NOT NULL,
    message_id BIGINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ephemeral_msgs (
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    channel_id BIGINT UNSIGNED NOT NULL,
    message_id BIGINT UNSIGNED NOT NULL,
    INDEX idx_channel (channel_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS command_perms (
    command_name VARCHAR(64)                                         NOT NULL PRIMARY KEY,
    tier         ENUM('everyone','server_admin','bot_admin')         NOT NULL DEFAULT 'everyone',
    hidden       BOOLEAN                                             NOT NULL DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0002_add_bot_command_usage_history.sql ──
-- 0002: per-cog daily command-usage snapshot, powering !graph commands.

CREATE TABLE IF NOT EXISTS bot_command_usage_history (
    snapshot_date VARCHAR(10) NOT NULL,
    cog_name      VARCHAR(64) NOT NULL,
    count         INT         NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_date, cog_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0003_add_activity_history.sql ──
-- 0003: per-user daily activity tables powering the !graph crime,
-- !graph gambling, and !graph levels subcommands.
--
-- Bundled in one migration because all three landed in the same dev cycle
-- before any deploy — splitting them would just be migration-file noise.

-- Coins gained/lost via !steal and !mug.
CREATE TABLE IF NOT EXISTS crime_history (
    snapshot_date VARCHAR(10)     NOT NULL,
    user_id       BIGINT UNSIGNED NOT NULL,
    gained        BIGINT          NOT NULL DEFAULT 0,
    lost          BIGINT          NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_date, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Net P/L from gambling (slots, flip, blackjack, scratchoff) and games
-- with payouts/wagers (hangman, ttt, c4, race, lottery).
CREATE TABLE IF NOT EXISTS gambling_history (
    snapshot_date VARCHAR(10)     NOT NULL,
    user_id       BIGINT UNSIGNED NOT NULL,
    gained        BIGINT          NOT NULL DEFAULT 0,
    lost          BIGINT          NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_date, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Per-(guild, user) daily count of level-ups. A single XP grant can cross
-- multiple level thresholds; the count column records boundaries crossed,
-- not events triggered.
CREATE TABLE IF NOT EXISTS levelup_history (
    snapshot_date VARCHAR(10)     NOT NULL,
    guild_id      BIGINT UNSIGNED NOT NULL,
    user_id       BIGINT UNSIGNED NOT NULL,
    count         INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_date, guild_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0004_add_bucket_column.sql ──
-- 0004: widen the 6 history tables with a `bucket` column so each calendar
-- day holds up to 4 data points (one per 6h CT window: 0=00-06, 1=06-12,
-- 2=12-18, 3=18-24). Existing rows backfill to bucket=0; the next 14 days
-- of writes will fill in the new buckets, and after the 14-day pruning
-- window all old daily rows naturally age out.
--
-- Each table needs three steps: add the column, drop the old PK, add the
-- new PK including bucket. Steps are split into separate statements so the
-- SQLite test translator (which doesn't support multi-action ALTER or PK
-- changes) can drop the PK statements and let SQLite use a permissive PK
-- — tests track PKs in tests/fakes/db.py:_TABLE_PKS for ON CONFLICT
-- translation, not via the SQLite engine's constraint.

ALTER TABLE balance_history ADD COLUMN bucket TINYINT NOT NULL DEFAULT 0;
ALTER TABLE balance_history DROP PRIMARY KEY;
ALTER TABLE balance_history ADD PRIMARY KEY (snapshot_date, bucket, user_id);

ALTER TABLE bot_stats_history ADD COLUMN bucket TINYINT NOT NULL DEFAULT 0;
ALTER TABLE bot_stats_history DROP PRIMARY KEY;
ALTER TABLE bot_stats_history ADD PRIMARY KEY (snapshot_date, bucket);

ALTER TABLE bot_command_usage_history ADD COLUMN bucket TINYINT NOT NULL DEFAULT 0;
ALTER TABLE bot_command_usage_history DROP PRIMARY KEY;
ALTER TABLE bot_command_usage_history ADD PRIMARY KEY (snapshot_date, bucket, cog_name);

ALTER TABLE crime_history ADD COLUMN bucket TINYINT NOT NULL DEFAULT 0;
ALTER TABLE crime_history DROP PRIMARY KEY;
ALTER TABLE crime_history ADD PRIMARY KEY (snapshot_date, bucket, user_id);

ALTER TABLE gambling_history ADD COLUMN bucket TINYINT NOT NULL DEFAULT 0;
ALTER TABLE gambling_history DROP PRIMARY KEY;
ALTER TABLE gambling_history ADD PRIMARY KEY (snapshot_date, bucket, user_id);

ALTER TABLE levelup_history ADD COLUMN bucket TINYINT NOT NULL DEFAULT 0;
ALTER TABLE levelup_history DROP PRIMARY KEY;
ALTER TABLE levelup_history ADD PRIMARY KEY (snapshot_date, bucket, guild_id, user_id);

-- ── 0005_add_user_perm_overrides.sql ──
-- 0005: per-(guild,user) permission tier overrides used by !setperm.
--
-- Each row promotes a specific user inside a specific guild to act as if
-- they held the named tier when permission checks run. tier is one of
-- 'user', 'server_admin', 'bot_admin'; a row with tier='user' is
-- equivalent to no override and is never written (the command deletes
-- the row instead). The (guild_id, user_id) pair is the PK so a user
-- has at most one override per guild.

CREATE TABLE IF NOT EXISTS user_perm_overrides (
    guild_id BIGINT      NOT NULL,
    user_id  BIGINT      NOT NULL,
    tier     VARCHAR(20) NOT NULL,
    PRIMARY KEY (guild_id, user_id)
);

-- ── 0006_add_blocklists.sql ──
-- 0006: bot-side blocklists used by !ban / !unban (per-guild) and
-- !globalban / !globalunban (bot-wide).
--
-- A row in blocklist silences a user inside a single guild — the bot
-- ignores their messages there (no AI reply, no command processing, no
-- XP/economy/tax/curse side effects). global_blocklist applies the same
-- silence everywhere. Discord membership is untouched; humans can still
-- talk to a banned user. server_admins and bot_admins are excluded from
-- being banned at the command layer (see is_bannable).

CREATE TABLE IF NOT EXISTS blocklist (
    guild_id   BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    reason     TEXT,
    banned_by  BIGINT      NOT NULL,
    banned_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (guild_id, user_id)
);

CREATE TABLE IF NOT EXISTS global_blocklist (
    user_id    BIGINT      NOT NULL,
    reason     TEXT,
    banned_by  BIGINT      NOT NULL,
    banned_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
);

-- ── 0007_add_jail_reason.sql ──
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS jail_reason VARCHAR(255) NULL;

-- ── 0008_add_crime_eligible.sql ──
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS crime_eligible BOOLEAN NOT NULL DEFAULT FALSE;

-- Backfill the wallet portion of the threshold. The savings JSON column is
-- not introspectable in pure SQL, so users whose savings push them over 100k
-- (without their wallet alone qualifying) will get latched on their next
-- add_balance / add_savings write. Level-based eligibility is latched by
-- the level-up path in src/leveling.py.
UPDATE economy_users SET crime_eligible = TRUE WHERE balance > 100000;

-- ── 0009_add_bail_amount.sql ──
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS bail_amount BIGINT NOT NULL DEFAULT 0;

-- ── 0010_add_issues.sql ──
-- 0010: persistent !bug / !issue reports.
--
-- Stores the bug-report embed reference so the on_raw_reaction_add handler
-- can find the row when a bot admin reacts with ✅, 🚧, or ❌ to mark the
-- issue completed / work-in-progress / rejected. status is persisted so a
-- reboot doesn't lose admin triage — the embed is re-rendered in the
-- matching color on the next status transition.

CREATE TABLE IF NOT EXISTS issues (
    id           BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    guild_id     BIGINT,
    channel_id   BIGINT      NOT NULL,
    message_id   BIGINT      NOT NULL UNIQUE,
    reporter_id  BIGINT      NOT NULL,
    report       TEXT        NOT NULL,
    status       VARCHAR(16) NOT NULL DEFAULT 'open',
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_by  BIGINT,
    resolved_at  TIMESTAMP   NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0011_add_error_mutes.sql ──
-- 0011: error-mute table for auto-filed command-error bug reports.
--
-- When a command raises, `_log_command_error` files an entry in `issues`
-- the same way !bugreport does, and seeds a 🔇 reaction. A bot admin
-- adding 🔇 inserts a row here keyed by (command, exception type, exception
-- message). Removing 🔇 deletes the row. Before filing a new auto-report
-- the error path consults this table; matches are dropped on the floor.
--
-- The companion `mute_key` column on `issues` lets the reaction handler
-- (a) skip mute UI for non-error issues and (b) render the muted/unmuted
-- footer without rebuilding the key.

CREATE TABLE IF NOT EXISTS error_mutes (
    mute_key    VARCHAR(255) NOT NULL PRIMARY KEY,
    muted_by    BIGINT       NOT NULL,
    muted_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE issues ADD COLUMN IF NOT EXISTS kind VARCHAR(16) NOT NULL DEFAULT 'bug';
ALTER TABLE issues ADD COLUMN IF NOT EXISTS mute_key VARCHAR(255);

-- ── 0012_add_issues_deleted.sql ──
-- 0012: soft-delete flag for issues hidden via `!issue delete <N>`.
--
-- Rather than DELETE the row (and lose the message_id binding that the
-- reaction listener depends on), soft-deletes set `deleted=1` and the
-- !issues listing filters them out. The embed itself is left untouched
-- in Discord and reactions on it become no-ops because get_issue_by_message
-- still resolves to a row that callers now ignore (or simply skip via
-- the deleted flag).

ALTER TABLE issues ADD COLUMN IF NOT EXISTS deleted TINYINT NOT NULL DEFAULT 0;

-- ── 0013_add_feature_requests.sql ──
-- 0013: feature_requests — user-submitted ideas reviewed in a per-guild
-- channel before being promoted into a feature issue.
--
-- Lifecycle:
--   • !featurerequest posts an embed into `feature_request_channel` and
--     inserts a row here with status='open'.
--   • A bot admin reacting ✅ flips status='accepted', spawns a kind='feature'
--     row in `issues`, and writes its id back into feature_issue_id.
--   • Reacting 🛑 flips status='rejected' (no feature issue is spawned).
--   • While a feature issue is linked, status-change reactions on the issue
--     re-render the request embed so the reporter can track progress.

CREATE TABLE IF NOT EXISTS feature_requests (
    id                BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    guild_id          BIGINT      NOT NULL,
    channel_id        BIGINT      NOT NULL,
    message_id        BIGINT      NOT NULL UNIQUE,
    reporter_id       BIGINT      NOT NULL,
    description       TEXT        NOT NULL,
    status            VARCHAR(16) NOT NULL DEFAULT 'open',
    feature_issue_id  BIGINT,
    created_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_by       BIGINT,
    resolved_at       TIMESTAMP   NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0014_add_issues_source_message.sql ──
-- 0014: persist the originating command message on each issue row.
--
-- channel_id/message_id refer to the embed posted in bug_report_channel
-- (admin-only). We also need to remember where the command that produced
-- the issue lives so the completion-DM jumplink lands the reporter in a
-- channel they can actually see (typically a public AI/game channel).
-- Pre-existing rows stay NULL and the DM falls back to a no-link body.

ALTER TABLE issues ADD COLUMN IF NOT EXISTS source_channel_id BIGINT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS source_message_id BIGINT;

-- ── 0015_rename_bug_report_channel_setting.sql ──
-- 0015: rename the global bot setting key from `bug_report_channel` to
-- `internal_issue_channel`. The channel's purpose has broadened beyond bug
-- reports (it now also hosts !issue feature/task/improvement embeds and
-- spawned feature issues from feature requests), so the user-facing setting
-- was renamed to match.
--
-- The migration runner records a checksum and only executes this file once,
-- so a plain UPDATE is safe — on second boot the schema_migrations row
-- prevents re-execution.

UPDATE bot_settings
   SET key_name = 'internal_issue_channel'
 WHERE key_name = 'bug_report_channel';

-- ── 0016_add_recap_usage.sql ──
-- 0016: recap_usage — per-user, per-guild daily-cap tracking for !recap.
--
-- !recap is `everyone` tier but limited to one run per user per guild per
-- 5am-CT "day". This table stores the last day-string a user ran it in;
-- the command compares it against `_ct_today()` and refuses if they match.
-- One row per (guild_id, user_id); the day string is overwritten on each
-- successful run, so the table never grows beyond the active user set.

CREATE TABLE IF NOT EXISTS recap_usage (
    guild_id   BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    last_date  VARCHAR(10) NOT NULL,
    PRIMARY KEY (guild_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0017_add_notable_events.sql ──
-- 0017: notable_events — a per-day event log of "things worth a recap quip"
-- that the all-time `records` table can't express.
--
-- The records table only stores each category's all-time best, with no
-- timestamp, so it can't answer "what records were set TODAY" — and a
-- lottery win that isn't a record isn't logged anywhere at all. This table
-- fills that gap: one row per notable moment, tagged with the 5am-CT day
-- string so !recap can pull just today's.
--
-- Written by:
--   • announce_record() in src/helpers.py — every record break (kind='record').
--   • the lottery draw in lottery_cog.py — every lottery win (kind='lottery_win').
-- Read by:
--   • !recap, via load_notable_events_today().
-- Pruned alongside the *_history tables in the daily reset (same cutoff).

CREATE TABLE IF NOT EXISTS notable_events (
    id           BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    guild_id     BIGINT       NOT NULL,
    event_day    VARCHAR(10)  NOT NULL,   -- 5am-CT "day" string, e.g. 2026-05-14
    kind         VARCHAR(24)  NOT NULL,   -- 'record' | 'lottery_win'
    category     VARCHAR(32),             -- record category (NULL for lottery_win)
    holder_name  VARCHAR(64)  NOT NULL,
    value        BIGINT       NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS idx_notable_events_guild_day
    ON notable_events (guild_id, event_day);

-- ── 0018_history_guild_scope.sql ──
-- 0018: add `guild_id` to crime_history and gambling_history so per-user
-- crime/gambling P/L is scoped per server, matching levelup_history.
--
-- Why: these two tables keyed on (snapshot_date, bucket, user_id) with no
-- guild — so a user's totals were summed across every server they play
-- in. !recap (and the !graph crime/gambling charts) then attributed one
-- server's activity to another. levelup_history already carries guild_id;
-- this brings the other two activity tables in line.
--
-- Existing rows have no guild — backfill to 0, a sentinel "unknown guild".
-- Pre-migration rows therefore never match a real guild_id in !recap or
-- !graph, which is correct: we genuinely don't know where they happened,
-- and they age out within the 14-day pruning window anyway.
--
-- Same three-step shape as 0004 (add column, drop PK, add PK) so the
-- SQLite test translator can handle it — it drops the DROP PRIMARY KEY
-- line and rebuilds the table on ADD PRIMARY KEY.

ALTER TABLE crime_history ADD COLUMN guild_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE crime_history DROP PRIMARY KEY;
ALTER TABLE crime_history ADD PRIMARY KEY (snapshot_date, bucket, guild_id, user_id);

ALTER TABLE gambling_history ADD COLUMN guild_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE gambling_history DROP PRIMARY KEY;
ALTER TABLE gambling_history ADD PRIMARY KEY (snapshot_date, bucket, guild_id, user_id);

-- ── 0019_add_voice_pings.sql ──
-- 0019: subscriptions for `!ping <voice_channel>` — DM the subscriber when a
-- voice channel goes from 0 humans to 1+. PK is (channel_id, user_id) so a
-- user can subscribe to many channels and a channel can have many subscribers.
--
-- last_pinged_at is a unix timestamp (seconds). It enforces the 30-minute
-- per-(channel,user) cooldown so a channel that's repeatedly emptying and
-- refilling doesn't spam the subscriber. NULL means "never pinged yet".
--
-- guild_id is stored alongside for guild-scoped listing in `!ping` with no
-- args — Discord channels carry a guild_id but we'd otherwise have to fetch
-- each channel just to filter the list.

CREATE TABLE IF NOT EXISTS voice_pings (
    guild_id        BIGINT NOT NULL,
    channel_id      BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    last_pinged_at  BIGINT,
    PRIMARY KEY (channel_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS idx_voice_pings_user ON voice_pings (user_id);
