-- AUTOGENERATED from migrations/. Do not edit this file directly.
-- To change the schema, add a new migrations/NNNN_description.sql file
-- and re-run scripts/regenerate_schema.py.
--
-- The bot itself applies pending migrations at boot — running this SQL
-- by hand against a live DB is no longer required.

-- ── 0001_baseline.sql ──
-- 0001_baseline: full schema as of the start of the migration system.
-- On an existing prod DB, this migration is detected as already-applied
-- (heuristic: economy_users present, schema_migrations empty) and recorded
-- without execution. On a fresh DB it creates everything below.

CREATE TABLE IF NOT EXISTS economy_users (
    user_id        BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    balance        BIGINT          NOT NULL DEFAULT 0,
    last_daily     DOUBLE          NOT NULL DEFAULT 0,
    daily_date     VARCHAR(10)     NULL,
    scratch_used   TINYINT         NOT NULL DEFAULT 0,
    scratch_date   VARCHAR(10)     NULL,
    jailbreak_used BOOLEAN         NOT NULL DEFAULT FALSE,
    jail_until     DOUBLE          NOT NULL DEFAULT 0,
    savings        JSON            NOT NULL DEFAULT (JSON_ARRAY())
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS economy_meta (
    key_name   VARCHAR(64) NOT NULL PRIMARY KEY,
    value_text TEXT        NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS guild_house_balance (
    guild_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    balance  BIGINT          NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS guild_settings (
    guild_id      BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    settings_json JSON            NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bot_roles (
    role_id BIGINT UNSIGNED NOT NULL PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS godmode_users (
    user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bot_settings (
    key_name   VARCHAR(64) NOT NULL PRIMARY KEY,
    value_text TEXT        NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS shop_insurance (
    user_id        BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    expires_at     DOUBLE          NOT NULL,
    protected_from JSON            NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS shop_effects (
    user_id      BIGINT UNSIGNED                           NOT NULL,
    effect_type  ENUM('ragebait','mock','curse','tax')     NOT NULL,
    remaining    INT          NULL,
    started_by   BIGINT UNSIGNED NULL,
    cursed_by    BIGINT UNSIGNED NULL,
    history_json JSON         NULL,
    master_id    BIGINT UNSIGNED NULL,
    tax_type     VARCHAR(64)  NULL,
    tax_emoji    VARCHAR(16)  NULL,
    channel_id   BIGINT UNSIGNED NULL,
    activated_at DOUBLE       NULL,
    PRIMARY KEY (user_id, effect_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rigged_slots (
    user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    symbol  VARCHAR(16)     NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rigged_flips (
    user_id        BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    remaining_wins INT             NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rigged_scratch (
    user_id       BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    symbols_count INT             NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rigged_steal (
    user_id              BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    remaining_successes  INT             NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS slots_jackpot (
    id      TINYINT NOT NULL PRIMARY KEY DEFAULT 1,
    jackpot BIGINT  NOT NULL DEFAULT 5000
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO slots_jackpot (id, jackpot) VALUES (1, 5000);

CREATE TABLE IF NOT EXISTS lottery (
    guild_id         BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    prize_pool       BIGINT          NOT NULL DEFAULT 0,
    last_posted_week INT             NOT NULL DEFAULT 0,
    last_drawn_week  INT             NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lottery_players (
    guild_id BIGINT UNSIGNED NOT NULL,
    user_id  BIGINT UNSIGNED NOT NULL,
    tickets  INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (guild_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS records (
    guild_id     BIGINT UNSIGNED NOT NULL,
    category     VARCHAR(64)     NOT NULL,
    value        BIGINT          NOT NULL,
    holder_id    BIGINT UNSIGNED NOT NULL,
    holder_name  VARCHAR(255)    NOT NULL,
    extra_json   JSON            NULL,
    PRIMARY KEY (guild_id, category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS channel_prompts (
    channel_id  BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    prompt_text TEXT            NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chess_games (
    channel_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    game_json  JSON            NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_threads (
    thread_id         BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    kind              ENUM('ask','story','roleplay','rpg') NOT NULL,
    owner_id          BIGINT UNSIGNED NOT NULL,
    guild_id          BIGINT UNSIGNED NULL,
    invited_ids_json  JSON            NOT NULL,
    system_prompt     TEXT            NULL,
    character_prompt  TEXT            NULL,
    history_json      JSON            NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS leveling (
    guild_id BIGINT UNSIGNED NOT NULL,
    user_id  BIGINT UNSIGNED NOT NULL,
    data     JSON            NOT NULL,
    PRIMARY KEY (guild_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS gambler_streak (
    user_id        BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    last_full_date VARCHAR(10)     NOT NULL,
    streak_count   INT             NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS quote_log (
    id         INT UNSIGNED    NOT NULL AUTO_INCREMENT PRIMARY KEY,
    content    TEXT            NOT NULL,
    created_at TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS saved_quotes (
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    guild_id   VARCHAR(20)     NOT NULL,
    quote_json JSON            NOT NULL,
    INDEX idx_guild (guild_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS balance_history (
    snapshot_date VARCHAR(10)     NOT NULL,
    user_id       BIGINT UNSIGNED NOT NULL,
    wallet        BIGINT          NOT NULL DEFAULT 0,
    savings       BIGINT          NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_date, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bot_stats_history (
    snapshot_date VARCHAR(10) NOT NULL PRIMARY KEY,
    messages      INT         NOT NULL DEFAULT 0,
    commands      INT         NOT NULL DEFAULT 0,
    ai_responses  INT         NOT NULL DEFAULT 0,
    ai_up         BOOLEAN     NOT NULL DEFAULT FALSE,
    memory_mb     FLOAT       NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS restart_msg (
    id         TINYINT         NOT NULL PRIMARY KEY DEFAULT 1,
    channel_id BIGINT UNSIGNED NOT NULL,
    message_id BIGINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ephemeral_msgs (
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    channel_id BIGINT UNSIGNED NOT NULL,
    message_id BIGINT UNSIGNED NOT NULL,
    INDEX idx_channel (channel_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS command_perms (
    command_name VARCHAR(64)                                         NOT NULL PRIMARY KEY,
    tier         ENUM('everyone','server_admin','bot_admin')         NOT NULL DEFAULT 'everyone',
    hidden       BOOLEAN                                             NOT NULL DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0002_add_bot_command_usage_history.sql ──
-- 0002: per-cog daily command-usage snapshot, powering !graph commands.

CREATE TABLE IF NOT EXISTS bot_command_usage_history (
    snapshot_date VARCHAR(10) NOT NULL,
    cog_name      VARCHAR(64) NOT NULL,
    count         INT         NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_date, cog_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0003_add_activity_history.sql ──
-- 0003: per-user daily activity tables powering the !graph crime,
-- !graph gambling, and !graph levels subcommands.
--
-- Bundled in one migration because all three landed in the same dev cycle
-- before any deploy — splitting them would just be migration-file noise.

-- Coins gained/lost via !steal and !mug.
CREATE TABLE IF NOT EXISTS crime_history (
    snapshot_date VARCHAR(10)     NOT NULL,
    user_id       BIGINT UNSIGNED NOT NULL,
    gained        BIGINT          NOT NULL DEFAULT 0,
    lost          BIGINT          NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_date, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Net P/L from gambling (slots, flip, blackjack, scratchoff) and games
-- with payouts/wagers (hangman, ttt, c4, race, lottery).
CREATE TABLE IF NOT EXISTS gambling_history (
    snapshot_date VARCHAR(10)     NOT NULL,
    user_id       BIGINT UNSIGNED NOT NULL,
    gained        BIGINT          NOT NULL DEFAULT 0,
    lost          BIGINT          NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_date, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Per-(guild, user) daily count of level-ups. A single XP grant can cross
-- multiple level thresholds; the count column records boundaries crossed,
-- not events triggered.
CREATE TABLE IF NOT EXISTS levelup_history (
    snapshot_date VARCHAR(10)     NOT NULL,
    guild_id      BIGINT UNSIGNED NOT NULL,
    user_id       BIGINT UNSIGNED NOT NULL,
    count         INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_date, guild_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0004_add_bucket_column.sql ──
-- 0004: widen the 6 history tables with a `bucket` column so each calendar
-- day holds up to 4 data points (one per 6h CT window: 0=00-06, 1=06-12,
-- 2=12-18, 3=18-24). Existing rows backfill to bucket=0; the next 14 days
-- of writes will fill in the new buckets, and after the 14-day pruning
-- window all old daily rows naturally age out.
--
-- Each table needs three steps: add the column, drop the old PK, add the
-- new PK including bucket. Steps are split into separate statements so the
-- SQLite test translator (which doesn't support multi-action ALTER or PK
-- changes) can drop the PK statements and let SQLite use a permissive PK
-- — tests track PKs in tests/fakes/db.py:_TABLE_PKS for ON CONFLICT
-- translation, not via the SQLite engine's constraint.

ALTER TABLE balance_history ADD COLUMN bucket TINYINT NOT NULL DEFAULT 0;
ALTER TABLE balance_history DROP PRIMARY KEY;
ALTER TABLE balance_history ADD PRIMARY KEY (snapshot_date, bucket, user_id);

ALTER TABLE bot_stats_history ADD COLUMN bucket TINYINT NOT NULL DEFAULT 0;
ALTER TABLE bot_stats_history DROP PRIMARY KEY;
ALTER TABLE bot_stats_history ADD PRIMARY KEY (snapshot_date, bucket);

ALTER TABLE bot_command_usage_history ADD COLUMN bucket TINYINT NOT NULL DEFAULT 0;
ALTER TABLE bot_command_usage_history DROP PRIMARY KEY;
ALTER TABLE bot_command_usage_history ADD PRIMARY KEY (snapshot_date, bucket, cog_name);

ALTER TABLE crime_history ADD COLUMN bucket TINYINT NOT NULL DEFAULT 0;
ALTER TABLE crime_history DROP PRIMARY KEY;
ALTER TABLE crime_history ADD PRIMARY KEY (snapshot_date, bucket, user_id);

ALTER TABLE gambling_history ADD COLUMN bucket TINYINT NOT NULL DEFAULT 0;
ALTER TABLE gambling_history DROP PRIMARY KEY;
ALTER TABLE gambling_history ADD PRIMARY KEY (snapshot_date, bucket, user_id);

ALTER TABLE levelup_history ADD COLUMN bucket TINYINT NOT NULL DEFAULT 0;
ALTER TABLE levelup_history DROP PRIMARY KEY;
ALTER TABLE levelup_history ADD PRIMARY KEY (snapshot_date, bucket, guild_id, user_id);

-- ── 0005_add_user_perm_overrides.sql ──
-- 0005: per-(guild,user) permission tier overrides used by !setperm.
--
-- Each row promotes a specific user inside a specific guild to act as if
-- they held the named tier when permission checks run. tier is one of
-- 'user', 'server_admin', 'bot_admin'; a row with tier='user' is
-- equivalent to no override and is never written (the command deletes
-- the row instead). The (guild_id, user_id) pair is the PK so a user
-- has at most one override per guild.

CREATE TABLE IF NOT EXISTS user_perm_overrides (
    guild_id BIGINT      NOT NULL,
    user_id  BIGINT      NOT NULL,
    tier     VARCHAR(20) NOT NULL,
    PRIMARY KEY (guild_id, user_id)
);

-- ── 0006_add_blocklists.sql ──
-- 0006: bot-side blocklists used by !ban / !unban (per-guild) and
-- !globalban / !globalunban (bot-wide).
--
-- A row in blocklist silences a user inside a single guild — the bot
-- ignores their messages there (no AI reply, no command processing, no
-- XP/economy/tax/curse side effects). global_blocklist applies the same
-- silence everywhere. Discord membership is untouched; humans can still
-- talk to a banned user. server_admins and bot_admins are excluded from
-- being banned at the command layer (see is_bannable).

CREATE TABLE IF NOT EXISTS blocklist (
    guild_id   BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    reason     TEXT,
    banned_by  BIGINT      NOT NULL,
    banned_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (guild_id, user_id)
);

CREATE TABLE IF NOT EXISTS global_blocklist (
    user_id    BIGINT      NOT NULL,
    reason     TEXT,
    banned_by  BIGINT      NOT NULL,
    banned_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
);

-- ── 0007_add_jail_reason.sql ──
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS jail_reason VARCHAR(255) NULL;

-- ── 0008_add_crime_eligible.sql ──
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS crime_eligible BOOLEAN NOT NULL DEFAULT FALSE;

-- Backfill the wallet portion of the threshold. The savings JSON column is
-- not introspectable in pure SQL, so users whose savings push them over 100k
-- (without their wallet alone qualifying) will get latched on their next
-- add_balance / add_savings write. Level-based eligibility is latched by
-- the level-up path in src/leveling.py.
UPDATE economy_users SET crime_eligible = TRUE WHERE balance > 100000;

-- ── 0009_add_bail_amount.sql ──
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS bail_amount BIGINT NOT NULL DEFAULT 0;

-- ── 0010_add_issues.sql ──
-- 0010: persistent !bug / !issue reports.
--
-- Stores the bug-report embed reference so the on_raw_reaction_add handler
-- can find the row when a bot admin reacts with ✅, 🚧, or ❌ to mark the
-- issue completed / work-in-progress / rejected. status is persisted so a
-- reboot doesn't lose admin triage — the embed is re-rendered in the
-- matching color on the next status transition.

CREATE TABLE IF NOT EXISTS issues (
    id           BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    guild_id     BIGINT,
    channel_id   BIGINT      NOT NULL,
    message_id   BIGINT      NOT NULL UNIQUE,
    reporter_id  BIGINT      NOT NULL,
    report       TEXT        NOT NULL,
    status       VARCHAR(16) NOT NULL DEFAULT 'open',
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_by  BIGINT,
    resolved_at  TIMESTAMP   NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0011_add_error_mutes.sql ──
-- 0011: error-mute table for auto-filed command-error bug reports.
--
-- When a command raises, `_log_command_error` files an entry in `issues`
-- the same way !bugreport does, and seeds a 🔇 reaction. A bot admin
-- adding 🔇 inserts a row here keyed by (command, exception type, exception
-- message). Removing 🔇 deletes the row. Before filing a new auto-report
-- the error path consults this table; matches are dropped on the floor.
--
-- The companion `mute_key` column on `issues` lets the reaction handler
-- (a) skip mute UI for non-error issues and (b) render the muted/unmuted
-- footer without rebuilding the key.

CREATE TABLE IF NOT EXISTS error_mutes (
    mute_key    VARCHAR(255) NOT NULL PRIMARY KEY,
    muted_by    BIGINT       NOT NULL,
    muted_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE issues ADD COLUMN IF NOT EXISTS kind VARCHAR(16) NOT NULL DEFAULT 'bug';
ALTER TABLE issues ADD COLUMN IF NOT EXISTS mute_key VARCHAR(255);

-- ── 0012_add_issues_deleted.sql ──
-- 0012: soft-delete flag for issues hidden via `!issue delete <N>`.
--
-- Rather than DELETE the row (and lose the message_id binding that the
-- reaction listener depends on), soft-deletes set `deleted=1` and the
-- !issues listing filters them out. The embed itself is left untouched
-- in Discord and reactions on it become no-ops because get_issue_by_message
-- still resolves to a row that callers now ignore (or simply skip via
-- the deleted flag).

ALTER TABLE issues ADD COLUMN IF NOT EXISTS deleted TINYINT NOT NULL DEFAULT 0;

-- ── 0013_add_feature_requests.sql ──
-- 0013: feature_requests — user-submitted ideas reviewed in a per-guild
-- channel before being promoted into a feature issue.
--
-- Lifecycle:
--   • !featurerequest posts an embed into `feature_request_channel` and
--     inserts a row here with status='open'.
--   • A bot admin reacting ✅ flips status='accepted', spawns a kind='feature'
--     row in `issues`, and writes its id back into feature_issue_id.
--   • Reacting 🛑 flips status='rejected' (no feature issue is spawned).
--   • While a feature issue is linked, status-change reactions on the issue
--     re-render the request embed so the reporter can track progress.

CREATE TABLE IF NOT EXISTS feature_requests (
    id                BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    guild_id          BIGINT      NOT NULL,
    channel_id        BIGINT      NOT NULL,
    message_id        BIGINT      NOT NULL UNIQUE,
    reporter_id       BIGINT      NOT NULL,
    description       TEXT        NOT NULL,
    status            VARCHAR(16) NOT NULL DEFAULT 'open',
    feature_issue_id  BIGINT,
    created_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_by       BIGINT,
    resolved_at       TIMESTAMP   NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0014_add_issues_source_message.sql ──
-- 0014: persist the originating command message on each issue row.
--
-- channel_id/message_id refer to the embed posted in bug_report_channel
-- (admin-only). We also need to remember where the command that produced
-- the issue lives so the completion-DM jumplink lands the reporter in a
-- channel they can actually see (typically a public AI/game channel).
-- Pre-existing rows stay NULL and the DM falls back to a no-link body.

ALTER TABLE issues ADD COLUMN IF NOT EXISTS source_channel_id BIGINT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS source_message_id BIGINT;

-- ── 0015_rename_bug_report_channel_setting.sql ──
-- 0015: rename the global bot setting key from `bug_report_channel` to
-- `internal_issue_channel`. The channel's purpose has broadened beyond bug
-- reports (it now also hosts !issue feature/task/improvement embeds and
-- spawned feature issues from feature requests), so the user-facing setting
-- was renamed to match.
--
-- The migration runner records a checksum and only executes this file once,
-- so a plain UPDATE is safe — on second boot the schema_migrations row
-- prevents re-execution.

UPDATE bot_settings
   SET key_name = 'internal_issue_channel'
 WHERE key_name = 'bug_report_channel';

-- ── 0016_add_recap_usage.sql ──
-- 0016: recap_usage — per-user, per-guild daily-cap tracking for !recap.
--
-- !recap is `everyone` tier but limited to one run per user per guild per
-- 5am-CT "day". This table stores the last day-string a user ran it in;
-- the command compares it against `_ct_today()` and refuses if they match.
-- One row per (guild_id, user_id); the day string is overwritten on each
-- successful run, so the table never grows beyond the active user set.

CREATE TABLE IF NOT EXISTS recap_usage (
    guild_id   BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    last_date  VARCHAR(10) NOT NULL,
    PRIMARY KEY (guild_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0017_add_notable_events.sql ──
-- 0017: notable_events — a per-day event log of "things worth a recap quip"
-- that the all-time `records` table can't express.
--
-- The records table only stores each category's all-time best, with no
-- timestamp, so it can't answer "what records were set TODAY" — and a
-- lottery win that isn't a record isn't logged anywhere at all. This table
-- fills that gap: one row per notable moment, tagged with the 5am-CT day
-- string so !recap can pull just today's.
--
-- Written by:
--   • announce_record() in src/helpers.py — every record break (kind='record').
--   • the lottery draw in lottery_cog.py — every lottery win (kind='lottery_win').
-- Read by:
--   • !recap, via load_notable_events_today().
-- Pruned alongside the *_history tables in the daily reset (same cutoff).

CREATE TABLE IF NOT EXISTS notable_events (
    id           BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    guild_id     BIGINT       NOT NULL,
    event_day    VARCHAR(10)  NOT NULL,   -- 5am-CT "day" string, e.g. 2026-05-14
    kind         VARCHAR(24)  NOT NULL,   -- 'record' | 'lottery_win'
    category     VARCHAR(32),             -- record category (NULL for lottery_win)
    holder_name  VARCHAR(64)  NOT NULL,
    value        BIGINT       NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS idx_notable_events_guild_day
    ON notable_events (guild_id, event_day);

-- ── 0018_history_guild_scope.sql ──
-- 0018: add `guild_id` to crime_history and gambling_history so per-user
-- crime/gambling P/L is scoped per server, matching levelup_history.
--
-- Why: these two tables keyed on (snapshot_date, bucket, user_id) with no
-- guild — so a user's totals were summed across every server they play
-- in. !recap (and the !graph crime/gambling charts) then attributed one
-- server's activity to another. levelup_history already carries guild_id;
-- this brings the other two activity tables in line.
--
-- Existing rows have no guild — backfill to 0, a sentinel "unknown guild".
-- Pre-migration rows therefore never match a real guild_id in !recap or
-- !graph, which is correct: we genuinely don't know where they happened,
-- and they age out within the 14-day pruning window anyway.
--
-- Same three-step shape as 0004 (add column, drop PK, add PK) so the
-- SQLite test translator can handle it — it drops the DROP PRIMARY KEY
-- line and rebuilds the table on ADD PRIMARY KEY.

ALTER TABLE crime_history ADD COLUMN guild_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE crime_history DROP PRIMARY KEY;
ALTER TABLE crime_history ADD PRIMARY KEY (snapshot_date, bucket, guild_id, user_id);

ALTER TABLE gambling_history ADD COLUMN guild_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE gambling_history DROP PRIMARY KEY;
ALTER TABLE gambling_history ADD PRIMARY KEY (snapshot_date, bucket, guild_id, user_id);

-- ── 0019_add_voice_pings.sql ──
-- 0019: subscriptions for `!ping <voice_channel>` — DM the subscriber when a
-- voice channel goes from 0 humans to 1+. PK is (channel_id, user_id) so a
-- user can subscribe to many channels and a channel can have many subscribers.
--
-- last_pinged_at is a unix timestamp (seconds). It enforces the 30-minute
-- per-(channel,user) cooldown so a channel that's repeatedly emptying and
-- refilling doesn't spam the subscriber. NULL means "never pinged yet".
--
-- guild_id is stored alongside for guild-scoped listing in `!ping` with no
-- args — Discord channels carry a guild_id but we'd otherwise have to fetch
-- each channel just to filter the list.

CREATE TABLE IF NOT EXISTS voice_pings (
    guild_id        BIGINT NOT NULL,
    channel_id      BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    last_pinged_at  BIGINT,
    PRIMARY KEY (channel_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS idx_voice_pings_user ON voice_pings (user_id);

-- ── 0020_chess_overhaul.sql ──
-- 0020: chess overhaul — replace JSON-blob chess_games with a column-per-field
-- schema, and add chess_reports for completed games.
--
-- Old chess_games stored the board as a JSON nested-list of Unicode glyphs plus
-- a list of UCI move strings. The new shape stores FEN (canonical board state,
-- restored on load with chess.Board(fen=...)) and PGN (full move history with
-- SAN). Active in-progress games at the time of this migration are dropped — no
-- reliable way to derive correct castling rights / en passant square from the
-- old board, and game count is small.
--
-- chess_reports archives finished games so `!chess view <id>` can replay them.
-- Active games (chess_games) are deleted on completion; only completed games
-- live in chess_reports.
--
-- Written by:
--   • cmd_chess / cmd_move_chess in src/games/chess.py — every move upserts
--     chess_games via save_chess_game(channel_id); game-end inserts a
--     chess_reports row and deletes the chess_games row.
-- Read by:
--   • init_db_state on boot, hydrating state.active_chess_games from the new
--     columns.
--   • !chess view <id>, via load_chess_report(report_id).

DROP TABLE IF EXISTS chess_games;

CREATE TABLE IF NOT EXISTS chess_games (
    channel_id    BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    fen           TEXT            NOT NULL,
    pgn           MEDIUMTEXT      NOT NULL,
    white_id      BIGINT UNSIGNED NOT NULL,
    black_id      BIGINT UNSIGNED NOT NULL,
    current_id    BIGINT UNSIGNED NOT NULL,
    amount        BIGINT          NOT NULL DEFAULT 0,
    last_move     VARCHAR(255)    NOT NULL DEFAULT '',
    board_msg_id  BIGINT UNSIGNED NULL,
    started_at    DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chess_reports (
    report_id    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    guild_id     BIGINT UNSIGNED NULL,
    channel_id   BIGINT UNSIGNED NOT NULL,
    white_id     BIGINT UNSIGNED NOT NULL,
    black_id     BIGINT UNSIGNED NOT NULL,
    winner_id    BIGINT UNSIGNED NULL,        -- NULL for draws
    result       VARCHAR(8)      NOT NULL,    -- '1-0' | '0-1' | '1/2-1/2'
    pgn          MEDIUMTEXT      NOT NULL,
    final_fen    TEXT            NOT NULL,
    finished_at  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS idx_chess_reports_white
    ON chess_reports (white_id);
CREATE INDEX IF NOT EXISTS idx_chess_reports_black
    ON chess_reports (black_id);
CREATE INDEX IF NOT EXISTS idx_chess_reports_finished
    ON chess_reports (finished_at);

-- ── 0021_add_chess_elo.sql ──
-- 0021: add `elo` to chess_games so bot-vs-human games resume at the right
-- strength after a bot restart. NULL for PvP games (no engine involved).

ALTER TABLE chess_games ADD COLUMN IF NOT EXISTS elo INT UNSIGNED NULL;

-- ── 0022_add_bot_chess_elo_tracking.sql ──
-- 0022: per-user daily-reset highwater for Stockfish bot defeats.
--
-- When a user beats the chess bot, they get paid 20 coins per NEW elo point
-- beyond their highest bot-elo-defeated TODAY. So beating a 400-elo bot,
-- then a 500-elo bot on the same day, pays (400)*20 + (500-400)*20 = 10000.
-- The next day's 5am CT reset zeroes the highwater, and the same 400 + 500
-- sequence pays out fully again.
--
-- bot_chess_elo_max_date is the 5am-CT day string. The loader treats a row
-- whose date != today as if max_today=0, so we don't need to depend on the
-- daily-reset task ever firing — stale rows self-heal on read.

ALTER TABLE economy_users
    ADD COLUMN IF NOT EXISTS bot_chess_elo_max_today INT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE economy_users
    ADD COLUMN IF NOT EXISTS bot_chess_elo_max_date VARCHAR(10) NULL;

-- ── 0023_add_bot_role_rank.sql ──
-- 0023: add per-guild rank to bot_roles so !shop roleup / !shop roledown can
-- swap adjacent ranks deterministically instead of comparing against Discord's
-- shared role.position (which includes non-bot roles and produced the
-- "#3 jumps to #1" bug when no other bot roles sat above the target).
--
-- New columns:
--   guild_id BIGINT UNSIGNED — which guild this role lives in. Role IDs are
--     globally unique, so we *could* keep PK as role_id and store guild_id as
--     a regular column, but ranking is inherently per-guild and the composite
--     PK matches that mental model.
--   rank_pos INT — 1 = highest in the bot-role ranking. Lower number = higher
--     rank. Gaps are allowed (the bot doesn't compact on delete). Named
--     rank_pos rather than `rank` to avoid the MariaDB 10.2+ reserved word.
--
-- Both default to 0 for existing rows; production data will be backfilled
-- manually by the operator. New rows written by !shop createrole get the
-- correct values from app code.

ALTER TABLE bot_roles ADD COLUMN IF NOT EXISTS guild_id BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE bot_roles ADD COLUMN IF NOT EXISTS rank_pos INT NOT NULL DEFAULT 0;
ALTER TABLE bot_roles DROP PRIMARY KEY;
ALTER TABLE bot_roles ADD PRIMARY KEY (guild_id, role_id);

-- ── 0024_add_chess_opening.sql ──
-- 0024: add `opening` to chess_games so the bot's chosen opening line
-- survives bot restarts. NULL means the bot is not following an opening
-- (either it never started one, or it has been abandoned mid-game).

ALTER TABLE chess_games ADD COLUMN IF NOT EXISTS opening VARCHAR(64) NULL;

-- ── 0025_add_chess_embed_msg_id.sql ──
-- 0025: add `embed_msg_id` to chess_games so the bot can delete BOTH the
-- prior board image AND the prior text/embed message when bumping the
-- board to the bottom of the channel. board_msg_id tracks the image
-- attachment message; embed_msg_id tracks the embed message that holds
-- the title/last-move/captures text.

ALTER TABLE chess_games ADD COLUMN IF NOT EXISTS embed_msg_id BIGINT UNSIGNED NULL;

-- ── 0026_drop_chess_opening.sql ──
-- 0026: drop chess_games.opening column. The opening-book system was
-- removed when the chess bot switched to Maia (which plays human-shaped
-- openings naturally — no scripted book needed). Migration 0024 added
-- this column; this migration drops it.

ALTER TABLE chess_games DROP COLUMN IF EXISTS opening;

-- ── 0027_add_chess_report_elo.sql ──
-- 0027: add `elo` to chess_reports so bot-game records can be bucketed by
-- the Elo at which the bot was playing. NULL = PvP game (no engine).
-- Used by load_bot_head_to_head to compute per-Elo win/loss records
-- between a human and the bot.

ALTER TABLE chess_reports ADD COLUMN IF NOT EXISTS elo INT UNSIGNED NULL;

-- ── 0028_add_chess_turn_timing.sql ──
-- 0028: track per-player thinking time in chess games. turn_started_at is
-- the UNIX timestamp (seconds since epoch) when the current player's turn
-- began; white_seconds and black_seconds are cumulative seconds spent
-- thinking. On each move the elapsed time since turn_started_at is added
-- to whichever player just moved, then turn_started_at resets.

ALTER TABLE chess_games ADD COLUMN IF NOT EXISTS turn_started_at BIGINT UNSIGNED NULL;
ALTER TABLE chess_games ADD COLUMN IF NOT EXISTS white_seconds INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE chess_games ADD COLUMN IF NOT EXISTS black_seconds INT UNSIGNED NOT NULL DEFAULT 0;

-- ── 0029_add_voice_ping_ignores.sql ──
-- 0029: per-subscriber ignore list for `!subscribe ignore <user>`. When the
-- member who triggers a voice channel's 0→1 human transition is in a
-- subscriber's ignore list, that subscriber is skipped WITHOUT consuming their
-- per-(channel,user) cooldown — a later, non-ignored trigger still pings.
--
-- Scope is per (guild, subscriber, ignored_user): ignoring someone suppresses
-- their pings across every channel you subscribe to in that guild, and only
-- for you. PK is (guild_id, user_id, ignored_user_id).

CREATE TABLE IF NOT EXISTS voice_ping_ignores (
    guild_id          BIGINT NOT NULL,
    user_id           BIGINT NOT NULL,
    ignored_user_id   BIGINT NOT NULL,
    PRIMARY KEY (guild_id, user_id, ignored_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0030_add_spellcheck_effect.sql ──
-- 0030: add the 'spellcheck' effect to shop_effects.effect_type so the
-- `!shop spellcheck @user` purchase can persist. Spellcheck is a time-based
-- effect like 'tax': the AI corrects the target's non-command messages for a
-- purchased number of days. It reuses the existing master_id (purchaser),
-- channel_id (purchase channel, unused for gating), remaining (days bought),
-- and activated_at (start time) columns. Re-running this MODIFY with the same
-- definition is a harmless no-op, so the migration stays idempotent-on-retry.
ALTER TABLE shop_effects
    MODIFY COLUMN effect_type ENUM('ragebait','mock','curse','tax','spellcheck') NOT NULL;

-- ── 0031_add_bounties.sql ──
-- 0031: persistent honor-based bounties (!shop bounty / !bounty).
--
-- A bounty is an escrowed coin reward posted in a guild's configured
-- bounty channel. The author sets an amount (held in escrow, deducted at
-- creation) and a free-text condition. Another user reacts 🙋 to submit a
-- claim; the author is DM'd accept/reject reactions. The full lifecycle —
-- claim submitted, accepted, rejected, contested, polled, expired — is
-- persisted here so the on_raw_reaction_add handler resolves rows after a
-- reboot (Discord re-delivers reaction events but the message cache is empty
-- until a message is touched) and the expiry background loop can settle
-- timed-out claims/contests/polls.
--
-- status values:
--   open      — posted, no active claim; author can self-claim (refund) or a
--               user can submit a claim.
--   pending   — a claim is in flight; author has been DM'd accept/reject.
--               claim_expires_at bounds it (1 week).
--   contesting — author rejected; claimant was asked to contest. Bounded by
--               contest_expires_at (3 days).
--   polling   — claimant contested; an @everyone poll is live in the channel.
--               Bounded by poll_expires_at (3 days), then tallied.
--   accepted  — paid out (terminal).
--   rejected  — rejected & not contested / lost poll / expired (terminal,
--               escrow refunded to author unless a partial poll payout went out).
--   cancelled — author self-claimed before any claim (terminal, refunded).
--
-- Columns shared across the flow:
--   message_id        — the bounty embed in the bounty channel (lookup key).
--   dm_message_id     — the accept/reject DM sent to the author.
--   contest_message_id— the contest-offer DM sent to the rejected claimant.
--   poll_message_id   — the @everyone poll message in the channel.
--   claimant_id       — the user whose claim is in flight / was accepted.

CREATE TABLE IF NOT EXISTS bounties (
    id                  BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    guild_id            BIGINT          NOT NULL,
    channel_id          BIGINT          NOT NULL,
    message_id          BIGINT          NOT NULL UNIQUE,
    author_id           BIGINT          NOT NULL,
    amount              BIGINT          NOT NULL,
    -- `condition` is a MariaDB reserved word — must be backticked here. (The
    -- runtime queries in src/persistence/bounties.py already backtick it.)
    `condition`         TEXT            NOT NULL,
    status              VARCHAR(16)     NOT NULL DEFAULT 'open',
    claimant_id         BIGINT,
    dm_message_id       BIGINT,
    contest_message_id  BIGINT,
    poll_message_id     BIGINT,
    poll_channel_id     BIGINT,
    claim_expires_at    DOUBLE,
    contest_expires_at  DOUBLE,
    poll_expires_at     DOUBLE,
    claim_log           JSON,
    created_at          DOUBLE          NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS idx_bounties_status ON bounties (status);
CREATE INDEX IF NOT EXISTS idx_bounties_dm_message ON bounties (dm_message_id);
CREATE INDEX IF NOT EXISTS idx_bounties_contest_message ON bounties (contest_message_id);
CREATE INDEX IF NOT EXISTS idx_bounties_poll_message ON bounties (poll_message_id);

-- ── 0032_effects_per_guild.sql ──
-- 0031: scope shop effects per-server and fold insurance into shop_effects.
--
-- Before this, shop_effects was keyed (user_id, effect_type) with no guild —
-- so a user could hold at most one of each effect across ALL servers, and an
-- effect bought in server A would fire in server B. Insurance lived in a
-- separate, also-global shop_insurance table. This migration:
--
--   1. adds guild_id to shop_effects and re-keys the PK to
--      (guild_id, user_id, effect_type) so each (guild, user) has its own set;
--   2. adds an expires_at column (used by time-based effects: insurance, and
--      future unification of tax/spellcheck) and widens the effect_type ENUM
--      to include 'insurance';
--   3. drops the old global shop_insurance table.
--
-- Existing rows in BOTH tables are dropped: they carry no guild_id and can't be
-- safely assigned to a server, and insurance/effects are short-lived anyway.
-- Users re-buy going forward; everything is per-server from here.
--
-- Three-step add/drop-PK/add-PK shape (like 0004/0018) so the SQLite test
-- translator can handle it. The MODIFY COLUMN that widens the ENUM is a no-op
-- in tests (ENUM is TEXT there) and the translator drops it.

DELETE FROM shop_effects;

ALTER TABLE shop_effects ADD COLUMN IF NOT EXISTS guild_id BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE shop_effects ADD COLUMN IF NOT EXISTS expires_at DOUBLE NULL;

ALTER TABLE shop_effects
    MODIFY COLUMN effect_type ENUM('ragebait','mock','curse','tax','spellcheck','insurance') NOT NULL;

ALTER TABLE shop_effects DROP PRIMARY KEY;
ALTER TABLE shop_effects ADD PRIMARY KEY (guild_id, user_id, effect_type);

DROP TABLE IF EXISTS shop_insurance;

-- ── 0033_bounty_concurrent_claims.sql ──
-- 0033: optional bounty expiration + concurrent per-claim tracking.
--
-- Two changes that go together (see src/cogs/bounty_cog.py):
--
-- 1. bounties.expires_at — an OPTIONAL overall deadline for an open bounty,
--    set via `!bounty <coins> <duration> <condition>` (e.g. `!bounty 5k 7d …`).
--    NULL means the bounty never times out. When the deadline passes while the
--    bounty is still open, it auto-closes and refunds the author 90% (the same
--    10% house cut taken on an author self-cancel). A bounty WITH a deadline
--    cannot be self-cancelled by the author — only a real claim or the deadline
--    resolves it.
--
-- 2. bounty_claims — claims are now first-class rows so a single bounty can
--    carry several concurrent claims (each its own author-DM, contest offer,
--    and @everyone poll). The bounty stays 'open' through all of them; the
--    FIRST accepted claim pays out, flips the bounty to 'accepted', and voids
--    every sibling claim (pending DMs ignored, any live poll edited to "void"
--    and skipped at tally). A failed claim (rejected, contest dropped/expired,
--    poll voted no) leaves the bounty open for others. A user gets at most one
--    claim per bounty, ever — enforced by the UNIQUE (bounty_id, claimant_id).
--
-- The legacy per-claim columns on `bounties` (claimant_id, dm_message_id,
-- contest_message_id, poll_message_id, poll_channel_id, claim_expires_at,
-- contest_expires_at, poll_expires_at) from 0031 are left in place but unused
-- by the new code; they're harmless nullable columns. The new `bounties.status`
-- vocabulary is open / accepted / cancelled / expired.

ALTER TABLE bounties
    ADD COLUMN IF NOT EXISTS expires_at DOUBLE NULL;

CREATE TABLE IF NOT EXISTS bounty_claims (
    id                  BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bounty_id           BIGINT          NOT NULL,
    claimant_id         BIGINT          NOT NULL,
    status              VARCHAR(16)     NOT NULL DEFAULT 'pending',
    dm_message_id       BIGINT,
    contest_message_id  BIGINT,
    poll_message_id     BIGINT,
    poll_channel_id     BIGINT,
    claim_expires_at    DOUBLE,
    contest_expires_at  DOUBLE,
    poll_expires_at     DOUBLE,
    created_at          DOUBLE          NOT NULL,
    -- Portable inline UNIQUE (MariaDB + SQLite test translator both accept this
    -- form; MariaDB's `UNIQUE KEY name (...)` is not SQLite-compatible). One
    -- claim per (bounty, user), ever — a rejected row stays and blocks reclaims.
    UNIQUE (bounty_id, claimant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS idx_bounty_claims_bounty ON bounty_claims (bounty_id);
CREATE INDEX IF NOT EXISTS idx_bounty_claims_dm ON bounty_claims (dm_message_id);
CREATE INDEX IF NOT EXISTS idx_bounty_claims_contest ON bounty_claims (contest_message_id);
CREATE INDEX IF NOT EXISTS idx_bounty_claims_poll ON bounty_claims (poll_message_id);

-- ── 0034_add_ping_ms.sql ──
-- 0034: Discord gateway heartbeat latency snapshot for `!graph ping`.
-- NULL means "not measured" (rows written before this column existed, or
-- snapshots taken before the first heartbeat ack after a reconnect).
ALTER TABLE bot_stats_history ADD COLUMN IF NOT EXISTS ping_ms FLOAT NULL;

-- ── 0035_add_mc_ping_samples.sql ──
-- Per-poll Minecraft monitor samples (one row per ~60s status ping).
-- Powers the !mc uptime/avg-ping stats across bot restarts and the
-- fine-grained last-7-days tail of !graph minecraft. The monitor loop
-- prunes rows older than its 7-day window, so the table stays ~10k rows.
CREATE TABLE IF NOT EXISTS mc_ping_samples (
    ts BIGINT NOT NULL,
    online TINYINT(1) NOT NULL,
    latency_ms DOUBLE NULL,
    PRIMARY KEY (ts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0036_add_daily_counters.sql ──
-- Generic per-gameplay-day counters, one row per (day, counter).
-- `day` is the 5am-CT rollover string from src.economy._ct_today(), so
-- counters reset with the rest of the daily economy state. First user:
-- the "lottery tickets sold today" presence status line, which previously
-- lived only in memory and restarted at 0 on every deploy.
CREATE TABLE IF NOT EXISTS daily_counters (
    day VARCHAR(10) NOT NULL,
    counter VARCHAR(64) NOT NULL,
    value BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (day, counter)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0037_add_mc_stats_columns.sql ──
-- 0037: persist the mc_up / mc_ping_ms keys snapshot_bot_stats has been
-- writing into the in-memory history dict since the Minecraft monitor
-- landed — save_bot_stats_history never persisted them and the loader
-- never selected them, so the older-than-7-days tail of !graph minecraft
-- (which reads these keys once mc_ping_samples has pruned) was always
-- empty. NULL means "unknown": monitor disabled, no sample yet this
-- bucket, or a row written before this migration.
ALTER TABLE bot_stats_history ADD COLUMN IF NOT EXISTS mc_up TINYINT(1) NULL;
ALTER TABLE bot_stats_history ADD COLUMN IF NOT EXISTS mc_ping_ms DOUBLE NULL;

-- ── 0038_add_bounty_poll_votes.sql ──
-- 0038: track bounty contest-poll votes as they are cast.
--
-- bounty_claims.poll_votes — JSON `{"yes": [user ids], "no": [user ids]}`
-- maintained by on_raw_reaction_add/remove while a claim is `polling`. The
-- poll embed renders a live tally from this column, and the close-time tally
-- reads it instead of trusting the message's reactions to still be accurate
-- (reactions can be cleared by a moderator or lost with a deleted message;
-- a reaction scan at close remains only as catch-up for votes cast while the
-- bot was offline). NULL for claims that never reached a poll.

ALTER TABLE bounty_claims
    ADD COLUMN IF NOT EXISTS poll_votes TEXT NULL;

-- ── 0039_add_user_artifacts.sql ──
-- Permanent per-user artifacts bought via !artifacts (shop). One row per
-- (user, artifact); quantity supports future stackable artifacts.
CREATE TABLE IF NOT EXISTS user_artifacts (
    user_id     BIGINT      NOT NULL,
    artifact_id VARCHAR(64) NOT NULL,
    quantity    INT         NOT NULL DEFAULT 1,
    PRIMARY KEY (user_id, artifact_id)
);

-- ── 0040_add_command_streak.sql ──
-- Sequential-day command-usage streak: bumped once per CT day (5am rollover)
-- the first time a user successfully runs any command. One row per user,
-- global (not guild-scoped), mirroring gambler_streak.
CREATE TABLE IF NOT EXISTS command_streak (
    user_id      BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    last_date    VARCHAR(10)     NOT NULL,
    streak_count INT             NOT NULL DEFAULT 1
);

-- ── 0041_add_mc_player_stats.sql ──
-- 0041: persistent Minecraft player tracking, powering the daily-players
-- overlay on !graph minecraft.
--
-- The Bedrock pong only carries player *counts* (never names — see the
-- minecraft_cog module docstring), so "joins" and "leaves" are count deltas
-- observed by the ~60s monitor poll. mc_player_events keeps every observed
-- count change; mc_daily_player_stats is the compact per-day rollup the
-- graph reads (peak concurrent players, cumulative joins, accumulated
-- player-seconds). Both are pruned by the monitor at a ~10-year horizon
-- (MC_PLAYER_STATS_RETENTION_DAYS), matching GRAPH_HISTORY_RETENTION_DAYS.
CREATE TABLE IF NOT EXISTS mc_player_events (
    ts BIGINT NOT NULL,
    delta INT NOT NULL,
    players INT NOT NULL,
    PRIMARY KEY (ts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mc_daily_player_stats (
    stat_date VARCHAR(10) NOT NULL,
    max_concurrent INT NOT NULL DEFAULT 0,
    total_joins INT NOT NULL DEFAULT 0,
    player_seconds DOUBLE NOT NULL DEFAULT 0,
    PRIMARY KEY (stat_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0042_add_mc_daily_ping_stats.sql ──
-- 0042: long-term daily Minecraft ping rollup.
--
-- mc_ping_samples keeps only 7 days of ~60s polls; this table preserves a
-- compact per-CT-day summary for ~10 years (pruned by the monitor at
-- MC_STATS_RETENTION_DAYS). Rows are written by the monitor's hourly
-- rollup only for COMPLETED days — the ongoing day stays in the sample
-- table until it finishes. Downtime polls count as ping 0, matching the
-- !graph minecraft line semantics, so min_ping 0 means the server was
-- offline at some point that day.
CREATE TABLE IF NOT EXISTS mc_daily_ping_stats (
    stat_date VARCHAR(10) NOT NULL,
    avg_ping DOUBLE NOT NULL,
    min_ping DOUBLE NOT NULL,
    max_ping DOUBLE NOT NULL,
    PRIMARY KEY (stat_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0043_add_lottery_discount_columns.sql ──
-- 0043: per-user daily lottery ticket discount. The first 10 tickets a user
-- buys each gameplay-day (5am CT rollover) cost half price; these columns
-- track how many discounted tickets were used and for which day, mirroring
-- the scratch_used/scratch_date pattern.
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS lottery_disc_used INT NOT NULL DEFAULT 0;
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS lottery_disc_date VARCHAR(10) NULL;

-- ── 0044_add_lottery_automatch.sql ──
-- 0044: lottery automatch. Users opt in with `!lottery automatch <max>`;
-- whenever another player's ticket total passes theirs, the bot auto-buys
-- tickets on their behalf to tie that total, never raising their own count
-- above max_tickets. Rows last one lottery: cleared with
-- `!lottery automatch off`, or wiped for the whole guild when the monthly
-- draw resets the pool.
CREATE TABLE IF NOT EXISTS lottery_automatch (
    guild_id    BIGINT UNSIGNED NOT NULL,
    user_id     BIGINT UNSIGNED NOT NULL,
    max_tickets INT             NOT NULL,
    PRIMARY KEY (guild_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── 0045_add_scratch_won_today.sql ──
-- 0045: per-user scratchoff winnings for the current gameplay-day (5am CT
-- rollover), mirroring the scratch_used/scratch_date pattern. Feeds the
-- "best scratchoff day" record — the combined payout of every card a user
-- scratches in one day, which is what !scratches / the dailies 🎟️ button
-- produce in a single batch.
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS scratch_won_today BIGINT NOT NULL DEFAULT 0;

-- ── 0046_sync_artifact_record_across_guilds.sql ──
-- 0046: make the "most artifacts owned" record consistent across servers.
--
-- Artifacts are global per user (user_artifacts is keyed by user alone), but
-- the record was only ever written into the guild the purchase happened in.
-- A user in two servers who bought everything in server A left server B
-- showing a stale, lower total. src/persistence/records.py now mirrors the
-- write into the holder's other guilds; this backfills the rows that were
-- already written wrong.
--
-- SQL has no view of Discord membership, so "active in a guild" is proxied by
-- a `leveling` row — grant_xp materializes one on a user's first command or
-- message in a guild, before any rate-limit early-return. This is the same
-- proxy `_mirror_guilds` uses at runtime, so the two agree on who counts.
--
-- Names come from whatever holder_name that user already has on a records row
-- (MAX() picks one deterministically when they differ); a user who has never
-- held any record anywhere has no name to write and is skipped. The runtime
-- mirror covers them on their next purchase.
--
-- Idempotent and raise-only: every write is guarded on the new value being
-- strictly greater, so a re-run is a no-op and no record is ever lowered.

-- 1. Raise rows whose holder is already right but whose count went stale.
UPDATE records
   SET value = (SELECT COALESCE(SUM(ua.quantity), 0)
                  FROM user_artifacts ua
                 WHERE ua.user_id = records.holder_id)
 WHERE category = 'total_artifacts'
   AND value < (SELECT COALESCE(SUM(ua.quantity), 0)
                  FROM user_artifacts ua
                 WHERE ua.user_id = records.holder_id);

-- 2. Take the record in guilds where an active user's true count beats the
--    row sitting there (or where no row exists yet). ROW_NUMBER picks a
--    single candidate per guild — biggest count, lowest user id on a tie —
--    so the upsert can't depend on row order when two users both beat it.
INSERT INTO records (guild_id, category, value, holder_id, holder_name)
SELECT guild_id, 'total_artifacts', value, holder_id, holder_name
  FROM (
        SELECT l.guild_id    AS guild_id,
               c.value       AS value,
               c.holder_id   AS holder_id,
               c.holder_name AS holder_name,
               ROW_NUMBER() OVER (PARTITION BY l.guild_id
                                  ORDER BY c.value DESC, c.holder_id ASC) AS rn
          FROM (
                SELECT t.holder_id AS holder_id,
                       t.value     AS value,
                       (SELECT MAX(r.holder_name)
                          FROM records r
                         WHERE r.holder_id = t.holder_id
                           AND r.holder_name IS NOT NULL) AS holder_name
                  FROM (
                        SELECT user_id AS holder_id, SUM(quantity) AS value
                          FROM user_artifacts
                         GROUP BY user_id
                       ) t
               ) c
          JOIN leveling l ON l.user_id = c.holder_id
         WHERE c.holder_name IS NOT NULL
       ) ranked
 WHERE rn = 1
    ON DUPLICATE KEY UPDATE
       holder_name = CASE WHEN VALUES(value) > records.value
                          THEN VALUES(holder_name) ELSE records.holder_name END,
       holder_id   = CASE WHEN VALUES(value) > records.value
                          THEN VALUES(holder_id)   ELSE records.holder_id   END,
       value       = GREATEST(records.value, VALUES(value));

-- ── 0047_sync_command_streak_record_across_guilds.sql ──
-- 0047: make the "longest daily command streak" record consistent across
-- servers. Same bug and same fix as 0046 — see that file's header for the
-- leveling-row membership proxy and the raise-only guarantee.
--
-- The streak differs from the artifact count in one way: it is a high-water
-- mark over a value that can drop. `command_streak.streak_count` resets to 1
-- the day you miss, so the live column is NOT authoritative for the record.
-- The candidate is therefore the greatest of (every value already recorded
-- for that user in any guild, their current live streak) — the live streak is
-- in the mix only to catch a streak that was bumped outside a guild and so
-- never reached the records table.
--
-- Unlike 0046 this honours UID_TIEBREAK_CATEGORIES: `command_streak` breaks
-- ties on the lower user id, matching `_beats` in src/persistence/records.py,
-- so a tie can displace a higher-uid incumbent.

INSERT INTO records (guild_id, category, value, holder_id, holder_name)
SELECT guild_id, 'command_streak', value, holder_id, holder_name
  FROM (
        SELECT l.guild_id    AS guild_id,
               c.value       AS value,
               c.holder_id   AS holder_id,
               c.holder_name AS holder_name,
               ROW_NUMBER() OVER (PARTITION BY l.guild_id
                                  ORDER BY c.value DESC, c.holder_id ASC) AS rn
          FROM (
                SELECT t.holder_id AS holder_id,
                       t.value     AS value,
                       (SELECT MAX(r.holder_name)
                          FROM records r
                         WHERE r.holder_id = t.holder_id
                           AND r.holder_name IS NOT NULL) AS holder_name
                  FROM (
                        SELECT holder_id, MAX(value) AS value
                          FROM (
                                SELECT holder_id, value
                                  FROM records
                                 WHERE category = 'command_streak'
                                 UNION ALL
                                SELECT user_id, streak_count
                                  FROM command_streak
                               ) u
                         GROUP BY holder_id
                       ) t
               ) c
          JOIN leveling l ON l.user_id = c.holder_id
         WHERE c.holder_name IS NOT NULL
       ) ranked
 WHERE rn = 1
    ON DUPLICATE KEY UPDATE
       holder_name = CASE WHEN VALUES(value) > records.value
                            OR (VALUES(value) = records.value
                                AND VALUES(holder_id) < records.holder_id)
                          THEN VALUES(holder_name) ELSE records.holder_name END,
       holder_id   = CASE WHEN VALUES(value) > records.value
                            OR (VALUES(value) = records.value
                                AND VALUES(holder_id) < records.holder_id)
                          THEN VALUES(holder_id)   ELSE records.holder_id   END,
       value       = GREATEST(records.value, VALUES(value));

-- ── 0048_add_property_system.sql ──
-- 0048: real-estate property system (!assets).
--
-- property_owners holds one row per OWNED property — the catalog itself lives
-- in code (src/properties.py), keyed by property_id. The PK on property_id is
-- the bot-wide uniqueness guarantee: every property has at most one owner
-- across all servers. list_price NULL means "not for sale"; a non-NULL value
-- is a live cross-server marketplace listing.
CREATE TABLE IF NOT EXISTS property_owners (
    property_id VARCHAR(64)     NOT NULL PRIMARY KEY,
    owner_id    BIGINT UNSIGNED NOT NULL,
    acquired_at DOUBLE          NOT NULL,
    list_price  BIGINT          NULL,
    listed_at   DOUBLE          NULL,
    INDEX idx_property_owner (owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Per-user revenue bookkeeping: property_paid_at is the timestamp revenue
-- last accrued FROM (stamped on every !daily payout); property_revenue_total
-- is the lifetime sum of property revenue banked (feeds !graph assets).
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS property_paid_at       DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS property_revenue_total BIGINT NOT NULL DEFAULT 0;

-- Graph history: per-(date, bucket, user) property book value and lifetime
-- revenue snapshots, alongside the existing wallet/savings columns.
ALTER TABLE balance_history ADD COLUMN IF NOT EXISTS assets        BIGINT NOT NULL DEFAULT 0;
ALTER TABLE balance_history ADD COLUMN IF NOT EXISTS asset_revenue BIGINT NOT NULL DEFAULT 0;

-- ── 0049_add_global_admin_tier.sql ──
-- 0049: add 'global_admin' to the command_perms tier ENUM.
--
-- df5935a introduced the global_admin tier (VALID_TIERS + command_perms.json)
-- but never widened this ENUM, so the boot-time JSON->DB reconciliation in
-- init_db_state failed with (1265, "Data truncated for column 'tier'") and
-- the bot came up dropping every message. MODIFY is idempotent — re-running
-- it just re-applies the same definition.
ALTER TABLE command_perms
    MODIFY COLUMN tier ENUM('everyone','server_admin','bot_admin','global_admin')
    NOT NULL DEFAULT 'everyone';

-- ── 0050_add_property_upgrades_and_names.sql ──
-- 0050: property upgrades + custom business names (!assets upgrade / rename).
--
-- `upgraded` marks that the owner bought the property's one predefined
-- upgrade (name/cost/boost are hardcoded per property in src/properties.py);
-- the upgrade's cost folds into the property's value and its boost into the
-- property's daily revenue. `custom_name` is an owner-chosen display name
-- for the business (NULL = catalog name); it travels with the deed on a
-- marketplace sale and is cleared when the bank buys the property back.
ALTER TABLE property_owners ADD COLUMN IF NOT EXISTS upgraded    BOOLEAN     NOT NULL DEFAULT FALSE;
ALTER TABLE property_owners ADD COLUMN IF NOT EXISTS custom_name VARCHAR(64) NULL;

-- ── 0051_add_insurance_sub.sql ──
-- 0051: insurance subscriptions (`!shop insurance sub` / `unsub`).
--
-- A subscription auto-renews the user's per-guild insurance for 24h at each
-- daily claim, charging SHOP_INSURANCE_COST out of the claim. It persists as
-- a shop_effects row with effect_type='insurance_sub' and NULL expires_at
-- (a subscription has no expiry — it lives until the user unsubscribes),
-- so all this migration does is widen the ENUM like 0030/0032 did.
-- Re-running the MODIFY with the same definition is a harmless no-op.
ALTER TABLE shop_effects
    MODIFY COLUMN effect_type ENUM('ragebait','mock','curse','tax','spellcheck','insurance','insurance_sub') NOT NULL;

-- ── 0052_add_chess_user_stats.sql ──
-- Per-user all-time bot-chess stats: the two chess-only ranks shown in
-- !profile and the match embeds (max single Elo defeated, cumulative Elo
-- defeated) plus the set of 1100+ Elo bins whose one-time first-defeat
-- bonus has been claimed (JSON int array).
CREATE TABLE IF NOT EXISTS chess_user_stats (
    user_id            BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    max_elo_defeated   INT             NOT NULL DEFAULT 0,
    total_elo_defeated BIGINT          NOT NULL DEFAULT 0,
    bonus_bins         TEXT            NOT NULL
);

-- Backfill both ranks from game history. In bot games the human always plays
-- White and chess_reports.elo is non-NULL, so a human bot-defeat is exactly
-- (elo IS NOT NULL AND winner_id = white_id). bonus_bins starts empty even
-- for past wins: first-defeat bonuses are earnable going forward only.
-- NOT EXISTS keeps a partial re-run from doubling total_elo_defeated.
INSERT INTO chess_user_stats (user_id, max_elo_defeated, total_elo_defeated, bonus_bins)
SELECT r.white_id, MAX(r.elo), SUM(r.elo), '[]'
FROM chess_reports r
WHERE r.elo IS NOT NULL AND r.winner_id = r.white_id
  AND NOT EXISTS (SELECT 1 FROM chess_user_stats s WHERE s.user_id = r.white_id)
GROUP BY r.white_id;

-- ── 0053_add_chess_report_analysis.sql ──
-- Post-game engine analysis on finished chess games: per-player accuracy
-- stats (ACPL, top-move match rate, estimated performance Elo) as JSON, and
-- the cheat-flag suspect user id for admin review. Both NULL for unanalyzed
-- games (pre-feature history, engine unavailable, or game too short).
ALTER TABLE chess_reports ADD COLUMN IF NOT EXISTS analysis_json TEXT NULL;
ALTER TABLE chess_reports ADD COLUMN IF NOT EXISTS flag_user_id BIGINT UNSIGNED NULL;

-- ── 0054_lottery_daily_ticket_rework.sql ──
-- 0054: lottery ticket rework. Bulk buying, the half-price discount, and
-- automatch are gone. Tickets now come from exactly three places:
--   * one 1,000-coin daily ticket per user per server (dailies 🎟️ button, or
--     a confirm prompt on !lottery when today's ticket is still unbought)
--   * one free ticket per week for beating a 500+ Elo chess bot
--   * one more free ticket per week if the win was at 1100+ Elo
-- lottery_ticket_grants tracks the gates: daily_day is the gameplay-day of
-- the user's last daily-ticket purchase in that guild; chess_week_500 /
-- chess_week_1100 hold the ISO week of the last free chess ticket claimed in
-- that guild. Mirrored into state.lottery_ticket_grants at boot.
CREATE TABLE IF NOT EXISTS lottery_ticket_grants (
    guild_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    daily_day VARCHAR(10) NULL,
    chess_week_500 VARCHAR(10) NULL,
    chess_week_1100 VARCHAR(10) NULL,
    PRIMARY KEY (guild_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Automatch existed to keep up with bulk buyers; with everyone capped at one
-- purchased ticket a day it has nothing to match. Feature removed.
DROP TABLE IF EXISTS lottery_automatch;

-- Half-price discount counters (migration 0043) are dead with the discount.
ALTER TABLE economy_users DROP COLUMN IF EXISTS lottery_disc_used;
ALTER TABLE economy_users DROP COLUMN IF EXISTS lottery_disc_date;

-- ── 0055_make_insurance_global.sql ──
-- 0055: make insurance bot-wide instead of per-server.
--
-- Insurance (and its subscription) now protects the holder in EVERY server,
-- like balances and artifacts. Rows keep living in shop_effects but under the
-- sentinel guild_id=0; the PK (guild_id, user_id, effect_type) then enforces
-- one global policy per user. Other effect types stay per-guild.
--
-- Data migration: collapse each user's per-guild insurance rows into one
-- guild_id=0 row carrying their LATEST expiry — nobody's coverage shrinks
-- anywhere they had it, and shorter overlapping policies fold into the
-- longest one. Multi-guild subscriptions collapse to a single sub (charged
-- once per daily claim now, not once per guild). protected_from is reset to
-- the canonical full list.
--
-- Idempotent / retry-safe: guild_id=0 insurance rows could not exist before
-- this migration (purchases always ran inside a guild), and the NOT IN guard
-- skips users whose global row was already written by a half-applied run.

INSERT INTO shop_effects (guild_id, user_id, effect_type, expires_at, history_json)
SELECT 0, user_id, 'insurance', MAX(expires_at),
       '["ragebait", "mock", "nickname", "role", "steal", "tax", "spellcheck"]'
  FROM shop_effects
 WHERE effect_type='insurance' AND guild_id<>0
   AND user_id NOT IN (SELECT user_id FROM shop_effects WHERE effect_type='insurance' AND guild_id=0)
 GROUP BY user_id;

DELETE FROM shop_effects WHERE effect_type='insurance' AND guild_id<>0;

INSERT INTO shop_effects (guild_id, user_id, effect_type)
SELECT 0, user_id, 'insurance_sub'
  FROM shop_effects
 WHERE effect_type='insurance_sub' AND guild_id<>0
   AND user_id NOT IN (SELECT user_id FROM shop_effects WHERE effect_type='insurance_sub' AND guild_id=0)
 GROUP BY user_id;

DELETE FROM shop_effects WHERE effect_type='insurance_sub' AND guild_id<>0;

-- ── 0056_chess_ticket_weekly_ceiling.sql ──
-- 0056: chess lottery tickets switch from two per-tier weekly gates
-- (chess_week_500/chess_week_1100) to a cumulative weekly ceiling: any chess
-- win (PvP included) is worth 1 ticket, beating a 600+ Elo bot 2, a 1100+
-- bot 3 — each win tops the winner up to its ceiling, never past 3/week.
-- chess_week holds the ISO week; chess_tickets counts what's been granted in
-- it. The old columns are dropped without a data copy: grants are still
-- closed by the TICKET_SALES_START_CT launch gate (9/1/2026), so no live
-- claims exist to carry over.
ALTER TABLE lottery_ticket_grants ADD COLUMN IF NOT EXISTS chess_week VARCHAR(10) NULL;
ALTER TABLE lottery_ticket_grants ADD COLUMN IF NOT EXISTS chess_tickets INT NOT NULL DEFAULT 0;
ALTER TABLE lottery_ticket_grants DROP COLUMN IF EXISTS chess_week_500;
ALTER TABLE lottery_ticket_grants DROP COLUMN IF EXISTS chess_week_1100;

-- ── 0057_add_daily_gamble_property.sql ──
-- Per-user dailies-stake preference. When FALSE (the default) the dailies
-- 🪙/🎰 reactions leave property revenue out of the flip/slots stake — it
-- still banks with the claim. Users opt in with `!daily property`.
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS daily_gamble_property BOOLEAN NOT NULL DEFAULT FALSE;

-- ── 0058_add_insurance_paid_since_claim.sql ──
-- Insurance-premium accrual counters, reported (and reset) by the next daily
-- claim: how much the 5am sweep charged, and how many renewals lapsed
-- unpaid, since the user's last claim.
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS ins_paid_since_claim BIGINT NOT NULL DEFAULT 0;
ALTER TABLE economy_users ADD COLUMN IF NOT EXISTS ins_lapsed_since_claim INT NOT NULL DEFAULT 0;

-- ── 0059_backfill_house_pot_into_active_lotteries.sql ──
-- 0059: backfill guild house pots into the active September 2026 lotteries.
--
-- Every fresh lottery is supposed to start at LOTTERY_SEED_POOL + that
-- guild's house pot (drain_bot_balance_into_lottery), but the lottery
-- scheduler had no before_loop gate on init_db_state: a tick landing after
-- the gateway was ready but before the DB load finished saw an empty
-- in-memory guild_house and drained 0, while the DB row kept its coins.
-- The 9/1/2026 6pm CT draws hit that window, so the September pools started
-- at the bare seed. The scheduler is gated now (src/cogs/lottery_cog.py);
-- this moves the stranded pots into the lotteries that started without them.
--
-- Scope: only lotteries running the September 2026 cycle — drawn and/or
-- announced under month key 202609. Guilds whose lottery is disabled or
-- still on an older cycle keep their house pot; the (fixed) drain moves it
-- when their next lottery actually starts. On any DB with no 202609 rows
-- (fresh installs, or a deploy after the October draw) this is a no-op.
--
-- Re-running the whole file is a no-op: after the first pass the in-scope
-- house balances are 0, so the add contributes nothing. The one unsafe
-- retry is a crash exactly between the two statements (the pool is
-- autocommit) — a rerun then adds the pot twice, so verify prize_pool
-- before rebooting a half-applied 0059.

UPDATE lottery
   SET prize_pool = prize_pool + COALESCE((SELECT g.balance
                                             FROM guild_house_balance g
                                            WHERE g.guild_id = lottery.guild_id), 0)
 WHERE last_drawn_week = 202609
    OR last_posted_week = 202609;

UPDATE guild_house_balance
   SET balance = 0
 WHERE guild_id IN (SELECT guild_id
                      FROM lottery
                     WHERE last_drawn_week = 202609
                        OR last_posted_week = 202609);

-- ── 0060_add_chess_unlocks.sql ──
-- Chess shop unlocks: per-user and global (no guild dimension, like the
-- economy). item_id is 'pieces:<key>' or 'board:<key>' from the catalog in
-- src/chess_shop.py. Cost-0 defaults (cburnett pieces, default board) are
-- owned by everyone and never written here.
CREATE TABLE IF NOT EXISTS chess_unlocks (
    user_id BIGINT NOT NULL,
    item_id VARCHAR(64) NOT NULL,
    PRIMARY KEY (user_id, item_id)
);

-- ── 0061_add_chess_elo_spent.sql ──
-- Spendable-Elo accounting for the chess shop: a user's spendable balance is
-- total_elo_defeated - elo_spent. total_elo_defeated stays a monotonic
-- lifetime stat (profile ranks, records) and is never decremented; unlock
-- purchases only ever raise elo_spent.
ALTER TABLE chess_user_stats
    ADD COLUMN IF NOT EXISTS elo_spent BIGINT NOT NULL DEFAULT 0;

-- ── 0062_add_chess_equipped.sql ──
-- Equipped chess cosmetics (!chess <name>): one row per user, global like
-- the chess_unlocks they come from. Values are renderer keys
-- (chess_render.PIECE_SET_KEYS / BOARD_THEMES); the renderer falls back to
-- its defaults on an unknown value, so a stale row can never break board
-- rendering.
CREATE TABLE IF NOT EXISTS chess_equipped (
    user_id BIGINT NOT NULL PRIMARY KEY,
    piece_set VARCHAR(32) NOT NULL DEFAULT 'cburnett',
    board_theme VARCHAR(32) NOT NULL DEFAULT 'default'
);

-- ── 0063_chess_ticket_monthly_period.sql ──
-- 0063: chess lottery tickets go monthly. The free chess-win ticket ceiling
-- (2 for beating a 600+ Elo bot, global per user) used to reset every ISO
-- week; it now resets with the lottery itself — the window opens at the
-- 1st-of-month 6pm CT draw and runs until the next one (lottery_period_key
-- in src/economy.py). chess_week becomes chess_period and holds the
-- "YYYY-MM" key of the month the lottery opened in, instead of a "YYYY-Www"
-- ISO week. CHANGE COLUMN IF EXISTS renames in place (data kept) and is a
-- no-op once the column is gone.
--
-- Data: free grants only started with the 9/1/2026 6pm CT relaunch
-- (TICKET_SALES_START_CT), so every existing week key belongs to the
-- September 2026 lottery — fold them into its period so tickets already
-- claimed keep counting against the ceiling. Deployed after the October
-- draw instead, those rows are simply stale (a fresh ceiling), which is what
-- an unconverted week key would have meant anyway. Re-running is a no-op:
-- no "YYYY-Www" keys remain after the first pass.
ALTER TABLE lottery_ticket_grants CHANGE COLUMN IF EXISTS chess_week chess_period VARCHAR(10) NULL;

UPDATE lottery_ticket_grants
   SET chess_period = '2026-09'
 WHERE chess_period LIKE '2026-W%';
